name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prepare dist for Surge
        run: |
          mkdir -p ./dist
          cp index.html styles.css ./dist/
          echo "johancicd.surge.sh" > ./dist/CNAME
          cp ./dist/index.html ./dist/200.html

      - name: Install Surge CLI
        run: npm install -g surge

      - name: Deploy to Surge.sh
        run: surge ./dist johancicd.surge.sh --token $SURGE_TOKEN
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
